apiVersion: v1
kind: ConfigMap
metadata:
  name: busybox-env
  namespace: default
data:
  # Key-value pairs, values can be used as e.g. env-vars
  greeting: "Hello from the ConfigMap"
  some_value: "This is another value"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-index
  namespace: default
data:
  # Values can also be entire files
  index.html: |
    <h1>Hello from ConfigMap</h1>