apiVersion: v1
kind: Pod
metadata:
  name: web-volume
  namespace: default
  labels:
    app: web
spec:
  containers:
    - name: nginx
      image: docker.io/library/nginx:stable
      volumeMounts: # 2. Volume with config files is mounted into pod at specified path
        - name: html
          mountPath: /usr/share/nginx/html
  volumes:
    - name: html
      configMap: # 1. All configmap fields will be loaded as files in this volume
        name: web-index
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: default
  labels:
    app: web
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80