apiVersion: v1
kind: Pod
metadata:
  name: busybox-secret
  namespace: default
spec:
  containers:
    - name: busybox
      image: docker.io/library/busybox:stable
      command: ["sh", "-c", "trap 'exit 0' TERM; sleep infinity & wait"]
      envFrom:
        # All keys of the secret are loaded as environment variables
        - secretRef:
            name: busybox-secret
      volumeMounts:
        # All keys are loaded as individual files in the container
        - name: secret
          mountPath: /etc/secret
          readOnly: true # Sane defaults, secrets should be read-only
  volumes:
    - name: secret
      secret:
        secretName: busybox-secret