apiVersion: v1
kind: Secret
metadata:
  name: busybox-secret
  namespace: default
type: Opaque # Opaque = generic secret content
stringData:
  # stringData is automatically base64 encoded and then stored in the 'data' field
  API_TOKEN: "s3cr3t-token"