apiVersion: v1
kind: Pod
metadata:
  name: kubectl-pod
  namespace: default
spec:
  serviceAccountName: customaccount
  containers:
    - name: kubectl-pod
      image: docker.io/bitnami/kubectl:latest
      command: ["sh", "-c", "trap 'exit 0' TERM; sleep infinity & wait"]