apiVersion: v1
kind: Pod
metadata:
  name: annotation-demo
spec:
  # Multiple containers with different log outputs
  containers:
    - name: app
      image: docker.io/library/nginx:stable
    - name: sidecar
      image: docker.io/library/busybox:stable
      command: ["sh", "-c", "trap 'echo terminating; exit 0' TERM; echo 'Hello World'; while true; do sleep 1 & wait $!; done"]