apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-cron
  namespace: default
spec:
  schedule: "*/1 * * * *" # every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: docker.io/library/busybox:stable
              command: ["sh", "-c", "date; echo Hello from CronJob"]
          restartPolicy: Never