apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-agent
  namespace: default
spec:
  selector:
    matchLabels:
      app: node-agent
  template:
    metadata:
      labels:
        app: node-agent
    spec:
      containers:
        - name: busybox
          image: docker.io/library/busybox:stable
          command: ["sh", "-c", "while true; do echo alive; sleep 3600; done"]