apiVersion: v1
kind: Pod
metadata:
  name: web-broken
  namespace: default
  labels:
    app: web-broken
    component: frontend
spec:
  containers:
    - name: nginx-broken
      # Container tag explicitly chosen to be non-existent
      image: docker.io/library/nginx:doesnotexist
      ports:
        - containerPort: 80