apiVersion: v1
kind: Pod
metadata:
  name: busybox-dynamic-pv
  namespace: default
spec:
  containers:
    - name: busybox
      image: docker.io/library/busybox:stable
      command: ["sh", "-c", "trap 'exit 0' TERM; sleep infinity & wait"]
      volumeMounts:
        - name: data
          mountPath: /usr/share/
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: busybox-data-dynamic